---
title: "Data cleaning Pilot 2 for Experiment 4 - Phase 1"
output: 
  html_document: 
    keep_md: yes
---

```{r packages, message=FALSE}
library(tidyverse)     # create plots with ggplot, manipulate data, etc.
library(broom.mixed)   # convert regression models into nice tables
library(modelsummary)  # combine multiple regression models into a single table
library(lme4)          # model specification / estimation 
library(lmerTest)      # provides p-values in the output
library(ggpubr)        # stile feature of ggplot
library(gghalves)      # do special plots in ggplot
library(kableExtra)    # for tables
```

## Import data
```{r import, message=FALSE}
# export values, not labels from qualtrics
d <- read_csv("./data/values.csv")
names(d)
```

```{r}
# inspect
head(d) # you can also use View(d)
# delete first two rows
d <- d %>% 
  slice(3: nrow(.)) 
```

## Attention check
```{r attention}
# attention check
table(d$attention, useNA = "always")
```

There is no failed attention check. 

```{r}
# filter to only valid attention check responses
d <- d %>% filter(attention == 5)
```

## Re-shape data

```{r}
# check all names and their order. 
names(d)
```

Make better variable names.

```{r}
# We want to remove the archeo / entom prefix for questions on the other disciplines

# Function to rearrange and replace names
# names(d) <- str_replace(names(d),  
#   pattern = "^(archeo|entom)_(phys|immu)(.*)$", 
#   replacement = "\\2_\\3"
# )
# 
# names(d)
```

```{r}
# clean and re-shape
d <- d %>% 
  # add an easy to read participant identifier
  mutate(id = 1:nrow(.)) %>% 
  # bring to long format
  pivot_longer(cols = c(starts_with("archeo"), starts_with("entom")), 
               names_to = "condition", values_to = "score") %>% 
  # separate conditions into CONVERGENCE_OUTCOME_STIMULUS
  separate_wider_delim(condition, "_", names = c("discipline", "outcome", "time"),
                       # make sure that it works also for archeo_comp_before
                       too_many = "merge"
                       ) %>% 
  # update discipline
  mutate(
    discipline = if_else(
      str_detect(outcome, "phys|immu"),       # Check if "phys" or "immu" is in 'outcome'
      str_extract(outcome, "phys|immu"),     # Extract the "phys" or "immu" value
      discipline                             # Keep existing 'discipline' value
    ),
    outcome = str_remove(outcome, "phys|immu")  # Remove "phys" or "immu" from 'outcome'
  ) %>% 
  # necessary because of the way we labeled
  drop_na(score) %>% 
pivot_wider(names_from = outcome, values_from = score) %>% 
  # create better variable names
  rename(competence = comp, 
         impressed = impress, 
         ) %>% 
  # all variables are coded as `character` - make key variables numeric
  mutate(across(c(contains("comp"), impressed, contains("trust")), as.numeric)
         )
```

## Add demographics

## Recode demographics

```{r, message=FALSE}
# prolific_demographics <- read_csv("./data/prolific.csv")
# 
# d <- left_join(d, prolific_demographics, by = c("PROLIFIC_PID" = "Participant id"))
```


```{r}
# d <- d %>% 
#   mutate(gender = case_when(Sex == "Male" ~ "male", 
#                             Sex == "Female" ~  "female", 
#                             .default = NA), 
#          age = as.numeric(Age)
#          ) 
```

## Export data

```{r}
# wide format
write_csv(d, "data/cleaned.csv")
```
